# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-12 08:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='img_profile',
            field=models.ImageField(blank=True, upload_to='profile'),
        ),
    ]
